### ISSUE TITLE
add a keyboard shortcut that allows the user to enter a directory

### ISSUE THREAD

**Issue by Verkeano** [kivattt/fen#7]
add a keyboard shortcut that allows the user to enter a directory
for example the button y would open a window that allows the user enter the directory `/home/user/Documents`

**Comment by kivattt** [comment]
good idea, ill make the `c` key do that

**Comment by kivattt** [comment]
Added in https://github.com/kivattt/fen/releases/tag/v1.6.0
let me know if you don't like Tab for scrolling through the autocomplete, I could add configuration to change it
![image](https://github.com/user-attachments/assets/6a3d1a1b-992d-4d4c-b004-9d6d6ff6330c)

**Comment by Verkeano** [comment]
I think autocomplete is a perfect feature for a short cut like this

**Comment by Verkeano** [comment]
> Added in https://github.com/kivattt/fen/releases/tag/v1.6.0 let me know if you don't like Tab for scrolling through the autocomplete, I could add configuration to change it ![image](https://private-user-images.githubusercontent.com/49201105/357708804-6a3d1a1b-992d-4d4c-b004-9d6d6ff6330c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTAzMzYsIm5iZiI6MTcyMzY1MDAzNiwicGF0aCI6Ii80OTIwMTEwNS8zNTc3MDg4MDQtNmEzZDFhMWItOTkyZC00ZDRjLWIwMDQtOWQ2ZDZmZjYzMzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1Y2ZhYjQ3Y2JjMzNmMzA3YjYzYTQxYjQ1MmRiMjg5MWJkMzI2OWY5OWEzOTk1OGMxY2EwODVhYzcwMGI2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awK6kGCm8KmJ6uH_M8WQsUZYSiFsNleFHnIJTm2HJYk)

what if you could make the window bigger so the autocomplete would fit and would look neater
