### ISSUE TITLE
adding a open in a window button

### ISSUE THREAD

**Issue by Verkeano** [kivattt/fen#9]
adding a keyboard shortcut to open a folder in a new window preferably `Ctrl O`
opening a folder in a new window will work the same as in file explorer
if you want you can replace it with a open in a new tab but i see that feature more difficult to add than the other

**Comment by kivattt** [comment]
I've been thinking about having tabs similar to what ranger has, but it would require quite a bit of refactoring...
I think an easier alternative could be to make the number keys (or maybe tab/shift+tab) jump to different folders instantly from the latest history.
it would be even more useful if the history is preserved in a file

i'm not sure how well it would work in practice, though (the navigation history code is far from perfect, so it might end up too unpredictable)

maybe you'd manually assign numbers to folders, or just have 2 keys: bookmark / go to bookmark, what do you think?

**Comment by Verkeano** [comment]
I'm not too familiar with the project structure but I'll make sure to try to do that

**Comment by kivattt** [comment]
You can configure bookmarks in your config.lua file now:
https://github.com/kivattt/fen/blob/453320a3301e2c4b623f5c26012b3d1eddba819e/config.lua#L35-L46
